### ISSUE TITLE
Rejalar bormi?

### ISSUE THREAD

**Issue by Zikoi5** [jsdocs-uz/jsdocs.uz#1]
Assalomu alaykum, juda yaxshi ish boshlabsizlar. Shu ishda o'z hissamni qo'shmoqchiman, shu sababli ish rejalashtirilganmi yoki biron bir roadmap bor tanishib chiqmoqchi edim. Oldindan rahmat

**Comment by 10xStartuper** [comment]
javaScript.info ven saytini bir boshidan tarjima qilyapmiz. Documnetatsiya saytiga tashrif buyurib, yo'q bo'lgan postlardan ketmaketlikda tarjima qilishingiz mumkin.
